name: Docker Build and Push

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t myimage .
    - name: Tag the image
      run: |
        docker tag myimage madhavpreeth123/myimage
    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push the image
      run: |
        docker push madhavpreeth123/myimage
    - name: fetching image
      run: docker pull madhavpreeth123/myimage
