name: Build and push Docker image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: wndows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t myimage .
    - name: Push the Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push myimage

   


    
    
