name: Dockerimage
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: uses code
        uses: actions/checkout@v2
      - name: build docker image
        run: docker build -t myimage .

    
    
