name: Build and push Docker image
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker
      run: |
        choco install docker-desktop -y
        docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_ACCESS_KEY }}"
    - name: Build the Docker image
      run: |
        docker build -t madhavpreeth123/myimage .
    - name: Push the Docker image
      run: |
        docker push madhavpreeth123/myimage
